THUMBNAILS_GENERATED_KEY = "thumbnails_generated"
TOTAL_IMAGES_KEY = "total_images" 
TOTAL_THUMBNAILS_KEY = "total_thumbnails"
IMAGES_PROCESSED_KEY = "images_processed"
TOTAL_IMAGE_COUNT_KEY = "total_image_count"
PREPARING_IMAGE_COUNT = "preparing_image_count"
PREPARING_TOTAL_COUNT = "preparing_total_count"