"""init

Revision ID: 5e69dc97a227
Revises: 
Create Date: 2025-11-27 01:54:30.833176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e69dc97a227'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_requests', sa.Column('clerk_id', sa.String(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='user_role'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::user_role"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('user', 'admin', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::user_role"))
    op.drop_column('access_requests', 'clerk_id')
    # ### end Alembic commands ###
